#! /usr/bin/env python
# itgk oeving 9 - oppg4

def matCreate(f):
    mat = []
    f = open(f, 'r')
    for i in range(5):
        for j in f.readlines():
            mat.append(j.split(',')[i])

    for i in mat:
        print i


matCreate('timeplan.csv')



